name: (ARCHIVED) Canard Test Runner
run-name: ${{ github.actor }} is running canard unit tests ğŸ¤–
on:
  workflow_dispatch:
jobs:
  canard-runner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests: [launch_detect]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}."
      - name: Install test environment
        run: |
          python -m pip install --upgrade pip
          pip install gcovr
      - name: Check out FCF repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: echo "ğŸ’¡ The mod repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Build and run the canard/${{ matrix.tests }} tests
        run: |
          cd ${{ github.workspace }}/test/app/canard/${{ matrix.tests }}
          make test
      - name: Check for fails.
        run: |
          cd ${{ github.workspace }}/test/app/canard/${{ matrix.tests }}
          tail -3 results.txt | grep "Result: PASS"
      - name: Consolidate ${{ matrix.tests }} artifacts
        run: mv ${{ github.workspace }}/test/app/canard/${{ matrix.tests }}/results.txt ${{ github.workspace }}/test/app/canard/${{ matrix.tests }}/coverage/results.txt
      - name: "Promote Artifacts"
        uses: actions/upload-artifact@v4
        id: promote-results
        with:
          name: ${{ matrix.tests }}-artifacts
          path: ${{ github.workspace }}/test/app/canard/${{ matrix.tests }}/coverage/
      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.promote-results.outputs.artifact-id }}'
      - run: echo "ğŸ This job's status is ${{ job.status }}."