name: Canard Test Runner
run-name: ${{ github.actor }} is running canard unit tests ğŸ¤–
on:
  release:
  pull_request:
  push:
    paths:
      - .github/**
      - app/canard/**
      - init/terminal/**
    branches:
      - main
      - integration/**
jobs:
  canard-runner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests: [launch_detect]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}."
      - name: Install test environment
        run: |
          python -m pip install --upgrade pip
          pip install gcovr
      - name: Check out FCF repository code
        uses: actions/checkout@v4
        with:
          path: Flight-Computer-Firmware
          submodules: 'true'
      - name: Check out lib repository code
        uses: actions/checkout@v4
        with:
          path: Flight-Computer-Firmware/lib
          repository: SunDevilRocketry/lib.git
          ref: main
          submodules: 'true'
      - run: echo "ğŸ’¡ The lib repository has been cloned to the runner."
      - name: Check out test repository code
        uses: actions/checkout@v4
        with:
          path: Flight-Computer-Firmware/test
          repository: SunDevilRocketry/test.git
          ref: main
          submodules: 'true'
      - run: echo "ğŸ’¡ The test repository has been cloned to the runner."
      - name: Check out mod repository code
        uses: actions/checkout@v4
        with:
          path: Flight-Computer-Firmware/mod
          repository: SunDevilRocketry/test.git
          ref: main
          submodules: 'true'
      - run: echo "ğŸ’¡ The mod repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Build and run the canard/${{ matrix.tests }} tests
        run: |
          cd Flight-Computer-Firmware/test/app/canard/${{ matrix.tests }}
          make test
      - name: Consolidate ${{ matrix.tests }} artifacts
        run: mv Flight-Computer-Firmware/test/app/canard/${{ matrix.tests }}/results.txt Flight-Computer-Firmware/test/app/canard/${{ matrix.tests }}/coverage/results.txt
      - name: "Promote Artifacts"
        uses: actions/upload-artifact@v4
        id: promote-results
        with:
          name: ${{ matrix.tests }}-artifacts
          path: Flight-Computer-Firmware/test/app/canard/${{ matrix.tests }}/coverage/
      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.promote-results.outputs.artifact-id }}'
      - run: echo "ğŸ This job's status is ${{ job.status }}."